CREATE DATABASE ecommers;
USE ecommers;

SELECT * FROM sales;

-- View all sales from a specific category

SELECT * FROM sales
WHERE Category="furniture";

-- Find total revenue generated by each product

SELECT product_name, SUM(sales) AS total_sales
FROM sales
GROUP BY Product_Name
ORDER BY total_sales DESC;

-- Top 5 products by quantity sold

SELECT product_name, SUM(quantity) AS Total_quantity
FROM sales
GROUP BY Product_Name
ORDER BY Total_quantity DESC
LIMIT 5;

-- Find months with the highest revenue

SELECT 
    DATE_FORMAT(order_date, '%Y-%m') AS month,
    SUM(sales) AS monthly_revenue
FROM sales
GROUP BY month
ORDER BY monthly_revenue DESC;

-- Sales by region

SELECT region, SUM(sales) AS total_sales
FROM sales
GROUP BY Region
ORDER BY total_sales DESC;

-- Orders with High Profit

SELECT order_id, product_name, profit
FROM sales
WHERE profit > 500
ORDER BY profit DESC;

-- Customer Spending Analysis

SELECT customer_id,
       SUM(sales) AS total_spent
FROM sales
GROUP BY customer_id
ORDER BY total_spent DESC;




